# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treenode',
            name='parentNode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tree_view.TreeNode'),
        ),
    ]
