# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree_view', '0002_auto_20151218_0414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treenode',
            name='backColor',
        ),
        migrations.RemoveField(
            model_name='treenode',
            name='color',
        ),
        migrations.RemoveField(
            model_name='treenode',
            name='href',
        ),
        migrations.RemoveField(
            model_name='treenode',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='treenode',
            name='selectable',
        ),
        migrations.RemoveField(
            model_name='treenode',
            name='selectedIcon',
        ),
    ]
